@AI_service_HostAddress_http = http://localhost:5284
@AI_service_HostAddress_https = https://localhost:7208

###
POST https://localhost:7208/TrainModel
Content-Type: application/json

{
  "tagIds": [
    "5b39efee-8d03-4e68-9df3-44ba375e8b7b"
  ],
  "content" : "Test2"
}