CREATE TABLE Payloads (
    Id UUID UNIQUE NOT NULL PRIMARY KEY,  
    Value TEXT NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE Tags (
    Id UUID UNIQUE NOT NULL PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL UNIQUE,   
    Description TEXT NOT NULL
);

CREATE TABLE PayloadTags (
    PayloadId UUID NOT NULL REFERENCES Payloads(Id) ON DELETE CASCADE,
    TagId UUID NOT NULL REFERENCES Tags(Id) ON DELETE CASCADE,
    PRIMARY KEY (PayloadId, TagId)
);

CREATE TABLE Vectors (
    Id UUID UNIQUE NOT NULL PRIMARY KEY,          
    PayloadId UUID NOT NULL REFERENCES Payloads(Id) ON DELETE CASCADE,                           
    VectorId UUID NOT NULL,                         
    CreatedAt TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE PendingTrains (
    Id UUID UNIQUE NOT NULL PRIMARY KEY,
    PayloadId UUID NOT NULL REFERENCES Payloads(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMPTZ DEFAULT now()
);
