@AI_service_HostAddress_http = http://localhost:5284
@AI_service_HostAddress_https = https://localhost:7208

###
POST https://localhost:7208/TrainModel
Content-Type: application/json

{
  "tagIds": [
    "7a7734b3-0879-4eab-98fa-5b0963676ef0"
  ],
  "content" : "Test2"
}