name: .NET CI – ml_service

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.302'

    - name: Restore
      run: dotnet restore src/ai_service/AI_service.csproj

    - name: Build
      run: dotnet build src/ai_service/AI_service.csproj --configuration Release --no-restore
